name: CI/CD

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: use nodejs 18.2
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm install
      - run: npm run build --if-present

  deploy:
    needs: build

    runs0n: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appfolder: "dist"
        env:
          HD_MONGO_URI: ${{ secrets.HD_MONGO_URI }}
          HD_JWT_SECRET: ${{ secrets.HD_JWT_SECRET }}
          HD_JWT_EXPIRES_IN: ${{ secrets.HD_JWT_EXPIRES_IN }}
